export type IconTypes =
  'sale' |
  'status' |
  'location-point' |
  'download-upload' |
  'route' |
  'url-rewrite' |
  'coefficient' |
  'point-download' |
  'point-upload' |
  'phone' |
  'leavings' |
  'role' |
  'refresh-change' |
  'picking' |
  'setting' |
  'email' |
  'storefront' |
  'share-branches' |
  'transfert' |
  'zoom-out' |
  'zoom-in' |
  'roles' |
  'link' |
  'users' |
  'storefront-outline' |
  'formatting-bold' |
  'partners' |
  'basket' |
  'send' |
  'camera-add' |
  'visible' |
  'bar-code' |
  'offer' |
  'shield-off' |
  'set-figures' |
  'sort' |
  'gift' |
  'poligon' |
  'faq' |
  'invisible' |
  'online-pay' |
  'attach-file' |
  'repeat-refresh' |
  'list' |
  'support' |
  'characteristic' |
  'star-outline' |
  'paragraph' |
  'percent' |
  'dice' |
  'map' |
  'comment-mark' |
  'add-to-card' |
  'cloud-off' |
  'double-arrow-left' |
  'double-arrow-down' |
  'double-arrow-up' |
  'double-arrow-right' |
  'filter-mark' |
  'tasks-done' |
  'dot-lists' |
  'camera-off' |
  'branches' |
  'smile' |
  'print' |
  'timer' |
  'like' |
  'empty-basket' |
  'delivery' |
  'unpin' |
  'attention' |
  'circle-cancel-outline' |
  'shield' |
  'menu-close' |
  'check-calendar' |
  'dislike' |
  'qr-zone' |
  'cancel-small' |
  'decimal-numbers' |
  'filter' |
  'statistics' |
  'integer' |
  'filter-sort' |
  'delete' |
  'loader' |
  'cancel' |
  'heart-outline' |
  'cart-outline' |
  'premium' |
  'user' |
  'money' |
  'orders' |
  'location' |
  'cart' |
  'numbered-lists' |
  'gps' |
  'menu' |
  'categories' |
  'home-outline' |
  'monitoring' |
  'wallet' |
  'exit' |
  'shopping-bag' |
  'login' |
  'contract' |
  'news' |
  'layers' |
  'landing' |
  'circle-cancel' |
  'box' |
  'camera' |
  'refand' |
  'arrow-down' |
  'comment' |
  'like-fill' |
  'star' |
  'edit' |
  'dislike-fill' |
  'rotate' |
  'arrow-downward' |
  'arrow-up-thin' |
  'arrow-back' |
  'home' |
  'moon' |
  'share' |
  'pin' |
  'heart-fill' |
  'search' |
  'time' |
  'warning' |
  'cloud' |
  'multiline-text' |
  'more' |
  'info' |
  'chevron-left' |
  'ok-small' |
  'ok' |
  'arrow-up' |
  'post' |
  'carrousel' |
  'right-alignment' |
  'center-alignment' |
  'rb-checked' |
  'left-alignment' |
  'circle-check' |
  'template' |
  'image' |
  'lock' |
  'document' |
  'arrow-right' |
  'toggle-off' |
  'ban' |
  'near-me-outline' |
  'chevron-down' |
  'card' |
  'cb-checked' |
  'file-copy' |
  'chevron-up' |
  'chevron-right' |
  'plus' |
  'near-me' |
  'short-text' |
  'minus' |
  'drop-down' |
  'dot' |
  'drop-up'